### ISSUE TITLE
报表页面不能正常加载静态资源

### ISSUE THREAD

**Issue by gh503** [jeecgboot/JimuReport#2183]
##### 版本号：1.4.0
Jeecg  Boot Version: 3.0
Spring Boot Version: 2.3.5.RELEASE (v2.3.5.RELEASE)
MySQL: 5.7

###### pom.xml
```xml
<!-- 积木报表 -->
<dependency>
	<groupId>org.jeecgframework.jimureport</groupId>
	<artifactId>jimureport-spring-boot-starter</artifactId>
	<version>1.4.0</version>
</dependency>
````

####### yaml配置
```yaml
spring:
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
#jeecg专用配置
minidao:
  base-package: org.jeecg.modules.jmreport.desreport.dao*
  #DB类型（mysql | postgresql | oracle | sqlserver| other）
  db-type: mysql
jeecg :
  shiro:
    excludeUrls: /test/jeecgDemo/demo3,/test/jeecgDemo/redisDemo/**,/category/**,/visual/**,/map/**,/jmreport/bigscreen2/**
  #大屏报表参数设置
  jmreport:
    mode: dev
    #数据字典是否进行saas数据隔离，自己看自己的字典
    saas: false
    #是否需要校验token
    is_verify_token: true
    #必须校验方法
    verify_methods: remove,delete,save,add,updatefun
#Mybatis输出sql日志
logging:
  level:
    org.jeecg.modules.system.mapper: info
    org.jeecg.modules.jmreport: info
```

##### 问题描述：
报表页面不能正常加载静态资源，不是微服务，FAQ未找到相同问题

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/65324074/a3aca537-3016-4d4b-9b6b-f61996b1a667)

##### 重现步骤：
正常启动，点击页面必现

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；
