### ISSUE TITLE
Saas模式添加数据源，提示成功，实际上失败

### ISSUE THREAD

**Issue by gh503** [jeecgboot/JimuReport#2191]
##### 版本号：1.6.5

```xml
		</dependency>
		<!-- 积木报表 -->
		<dependency>
			<groupId>org.jeecgframework.jimureport</groupId>
			<artifactId>jimureport-spring-boot-starter</artifactId>
			<version>1.6.5</version>
		</dependency>
```

##### 问题描述：Saas模式已经配置数据源，报表设计页面没有显示出来；添加数据源，提示成功，实际上失败
![image](https://github.com/jeecgboot/JimuReport/assets/65324074/18ef5c13-f259-4ba8-ae87-e2ddf9153eb4)

```yaml

  #大屏报表参数设置
  jmreport:
    #多租户模式，默认值为空(created:按照创建人隔离、tenant:按照租户隔离) (v1.6.2+ 新增)
    saasMode: tenant
    # 平台上线安全配置(v1.6.2+ 新增)
    firewall:
      # 数据源安全 (开启后，不允许使用平台数据源、SQL解析加签并且不允许查询数据库)
      dataSourceSafe: false
      # 低代码开发模式（dev:开发模式，prod:发布模式—关闭在线报表设计功能，分配角色admin、lowdeveloper可以放开限制）
      lowCodeMode: dev
    #是否 禁用导出PDF和图片的按钮 默认为false
    exportDisabled: false
    #是否自动保存
    autoSave: true
    #自动保存间隔时间毫秒
    interval: 20000
    # 列数(设计页面展示多少列)
    col: 100
    #自定义项目前缀
    customPrePath:
    #数据源标识
    datasource: master
    #预览分页自定义
    pageSize:
      - 10
      - 20
      - 30
      - 40
    #接口超时设置（毫秒）
    connect-timeout: 300000
    #Excel导出模式(fast/快、primary/精致模式，默认fast)
    export-excel-pattern: fast
    #Excel导出数据每个sheet的行数,每个sheet最大1048576行
    page-size-number: 10000
    #设计页面表格的线是否显示 默认true
    line: true
    #是否需要校验token
    is_verify_token: true
    #必须校验方法
    verify_methods: remove,delete,save,add,updatefun
```

##### 错误日志&截图：
![T{AC`P2)HBV9M%BB6(0)@_5](https://github.com/jeecgboot/JimuReport/assets/65324074/db38d3d1-cfa1-41d0-9b91-4b0cfa20d8e6)
![ZDCQFYYY$FPUK~EYNS(2`BO](https://github.com/jeecgboot/JimuReport/assets/65324074/878bc47c-ccb4-48d3-a0a1-edcc221d9138)
![JZ%1(F{ 3(J3R Y410{VX9D](https://github.com/jeecgboot/JimuReport/assets/65324074/467c47fa-5fed-46ed-9afa-448978335696)

##### 重现步骤：
添加数据源

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；
