### ISSUE TITLE
快速集成后无法打开预览界面

### ISSUE THREAD

**Issue by pandichao** [jeecgboot/JimuReport#525]
##### 版本号：

1.3.795

##### 问题描述：

首先是一个springboot空工程快速集成的jimu报表，测试一下，是可以预览等使用的，但是当集成到现有框架模块中的时候，发现无法使用预览功能，控制台无报错日志，前端一直在加载中，且两个工程的配置是copy的，数据库也是同一个数据库

##### 错误日志&截图：

浏览器界面如下:
![image](https://user-images.githubusercontent.com/28852823/132322834-7d5e5bef-9c14-41de-9c68-0aece2d8d3a4.png)

后台代码控制台输出如下(info):
![image](https://user-images.githubusercontent.com/28852823/132322889-7f42a1fa-810a-42dc-b292-eabb4ac316a8.png)

##### 重现步骤：

大概贴一下配置项:

>pom配置

```xml
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.5</version>
		<relativePath/>
	</parent>

        <groupId>com.hearyou</groupId>
	<artifactId>ihap-jimu-report</artifactId>
	<version>${ihap.version}</version>
	<name>${artifactId}</name>
	<description>ihap-积木报表</description>
	<packaging>jar</packaging>

       <properties>
            <java.version>1.8</java.version>
            <common.version>1.0</common.version>
            <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
       </properties>
       
        <repositories>
		<repository>
			<id>aliyun</id>
			<name>aliyun Repository</name>
			<url>http://maven.aliyun.com/nexus/content/groups/public</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>jeecg</id>
			<name>jeecg Repository</name>
			<url>http://maven.jeecg.org/nexus/content/repositories/jeecg</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>

      <dependencyManagement>
		<dependencies>
			<!--cloud alibaba 2021 + Cloud 2020.0-->
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>2020.0.3</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<dependency>
				<groupId>com.alibaba.cloud</groupId>
				<artifactId>spring-cloud-alibaba-dependencies</artifactId>
				<version>2021.1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

      <dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>

		<!--默认springCloud 2020开始移除了bootstrap.yaml的启动引导项，不添加无法启动-->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-bootstrap</artifactId>
			<version>3.0.3</version>
		</dependency>

		<dependency>
			<groupId>javax.inject</groupId>
			<artifactId>javax.inject</artifactId>
			<version>1</version>
		</dependency>

		<!--jackson依赖包-->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
		</dependency>

                <!--nacos注册中心 依赖-->
		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
		</dependency>

		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
		</dependency>

		<!--RPC注册 nacos-->
		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-dubbo</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jeecgframework.jimureport</groupId>
			<artifactId>jimureport-spring-boot-starter</artifactId>
			<!--<version>1.3.78</version>-->
			<version>1.3.795</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-freemarker</artifactId>
		</dependency>

                <!--数据库依赖-->
		<dependency>
			<groupId>com.oracle</groupId>
			<artifactId>ojdbc6</artifactId>
			<version>11.2.0.3</version>
		</dependency>

		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<scope>runtime</scope>
		</dependency>
	</dependencies>

    <build>
           <plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
                                <version>3.8.1</version>
				<configuration>
				    <source>${java.version}</source>
				    <target>${java.version}</target>
				    <encoding>${project.build.sourceEncoding}</encoding>
                                </configuration>
			</plugin>
		</plugins>

               <resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>

			<resource>
				<directory>src/main/resources</directory>
			</resource>

			<resource>
				<directory>src/main/java</directory>
				<filtering>false</filtering>
				<includes>
					<include>**/mapper/*.xml</include>
				</includes>
			</resource>
		</resources>
      </build>
```

> bootstrap.yml 配置如下

```yaml
dubbo:
  application:
    name: ${spring.application.name}
    id: ${spring.application.name}
  scan:
    base-packages: com.hearyou.ihap.customer.service.impl
  protocol:
    name: dubbo
    port: -1
  registry:
    #作为服务发布注册的地址，指定使用springCloud的配置作为注册地址
    address: spring-cloud://localhost
  cloud:
    #作为消费者能调用到哪些服务的订阅(服务提供方的应用名称的列表，若需订阅多应用，使用 "," 分割)
    subscribed-services:
  consumer:
    timeout: 30000
    retries: -1

#Minidao配置
minidao:
  base-package: org.jeecg.modules.jmreport.*

#JimuReport[上传配置]
jeecg :
  # local|minio|alioss
  uploadType: local
  # local
  path :
    #文件路径
    upload: D:\opt\upload
  # alioss
  oss:
    endpoint: ??
    accessKey: ??
    secretKey: ??
    bucketName: jimureport
  # minio
  minio:
    minio_url: http://minio.jeecg.com
    minio_name: ??
    minio_pass: ??
    bucketName: ??

spring:
  application:
    name: @project.name@
    profiles:
      active: dev
    main:
      allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.123:18848
        namespace: hap-dev
        username: nacos-b2b
        password: nacos-b2b
        group: IHAP
      config:
        server-addr: 192.168.1.123:18848
        namespace: hap-dev
        group: IHAP
        prefix: ihap-jimu-report
        file-extension: yaml
        refresh: true

#输出sql日志
logging:
  level:
    org.jeecg.modules.jmreport : info
```

> nacos上的配置文件 ihap-jimu-report.yaml内容大概如下:

```yaml
server:
  port: 10800

spring:
  #配置静态资源
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/
  #配置数据库
  datasource:
    url: jdbc:mysql://${mysql-url:192.168.1.123.10}:${mysql-port:13306}/${mysql-db:jimu_report}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: ${mysql.username:dev_admin}
    password: ${mysql.password:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
```

> 启动类  ReportApplication内容如下:

```java
@EnableDiscoveryClient
@SpringBootApplication(scanBasePackages = {"com.hearyou.report","org.jeecg.modules.jmreport"})
@Slf4j
public class ReportApplication {

    public static void main(String[] args) {
        ConfigurableApplicationContext applicationContext = SpringApplication.run(ReportApplication.class);
        Environment env = applicationContext.getEnvironment();
        String port = env.getProperty("server.port");
        String path = env.getProperty("server.servlet.context-path");
        if(StrUtil.isBlank(path)){
            path = "";
        }else{
            if(!path.startsWith("/")){
                path = "/".concat(path);
            }
        }

        log.info("ReportApplication is running!URL:\t\t http://localhost:{}{}/jmreport/list",port,path);
    }
}
```
>补充说明

前端日志对比，我的工程集成完毕后，浏览器控制台报错，如下:
![image](https://user-images.githubusercontent.com/28852823/132440164-ed60a251-0c25-4227-aebf-49a0a6b1b3e2.png)

官方demo的控制台日志输出如下:
![image](https://user-images.githubusercontent.com/28852823/132440213-b377c460-dcf3-4ae9-b3df-aa9fba1c05f7.png)

test:开头的部分开始都是没有的，因为代码不开源的原因，无法排查前端，仅作为参考辅助，除此之外，两个工程的后台日志完全一样，并且浏览器network显示的响应也都是一样，每个接口都成功返回响应，日志如下:
![image](https://user-images.githubusercontent.com/28852823/132440343-7bfd8e0d-9a3e-41a7-8f5d-d1ec3067e608.png)

![image](https://user-images.githubusercontent.com/28852823/132440424-c2164e93-e900-41f4-b88e-574d01b62822.png)
可以看到，这个接口响应的应该就是前端渲染的报表数据，已经正常返回了，只是result下面的dataList字段获取不到，导致undefind
