### ISSUE TITLE
报表设计界面插入图片失败

### ISSUE THREAD

**Issue by libo5209** [jeecgboot/JimuReport#529]
##### 问题描述：报表设计界面**插入图片**失败

1.自定义项目前缀**customPrePath**，插入图片上传接口没有添加自定义项目前缀

##### 错误日志&截图：
![image](https://user-images.githubusercontent.com/40787669/132609918-b2fec89c-232e-408e-9447-452e82bbcd3b.png)

##### 重现步骤：
1.项目为微服务项目，报表为单独的一个微服务，前缀为cloud-report
2. 在yaml文件中配置
```yaml
jeecg :
  jmreport:
    #自定义项目前缀
    customPrePath:cloud-report
```
3. 在报表设计界面，插入图片，上传接口没有添加`cloud-report`【其它请求都是添加了前缀的】
